export const STORE_CHANGE_EVENT = 'STORE_CHANGE_EVENT'

export const ADD_ARTICLE = 'ADD_ARTICLE'

export const LOAD_ARTICLE_START = 'LOAD_ARTICLE_START'
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS'
export const LOAD_ARTICLE_FAIL = 'LOAD_ARTICLE_FAIL'